---
title: "how_to_make_a_poster"
author: "Toshikazu, Matsumura"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{how_to_make_a_poster}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tidyverse)
library(grid)
library(gridtext)
library(ggposter)
```

```{r}
  # plot
plot <- 
  ggplot2::ggplot(mpg) + 
  ggplot2::geom_point(aes(x = displ, y = hwy)) +
  ggplot2::theme_bw()
plot  # draw ggplot object

  # text
t_1 <- "This is a sample text. "
t_2 <- "When longer than width, "
t_3 <- "text will be split and add breaks. "
t_4 <- "This text is separated into 5 objects, "
t_5 <- "because of R document specification."
text <- stringr::str_c(t_1, t_2, t_3, t_4, t_5)
  # gp_text
fontsize <- 20
lineheight <- 1.1
gp_text <- gpar(fontsize=fontsize, lineheight=lineheight)

  # title
title <- "THIS IS TITLE WORDS"
  # gp_text
fontsize <- 40
gp_title <- gpar(fontsize=fontsize)

slide <- gen_slide(title, plot, text, gp_title, gp_text)
grid.draw(slide)
ggplot2::ggsave("d:/slide.pdf", slide, height=210, width=297, units="mm")

```

```{r richtext_grob}
grid::grid.newpage()
rtg <- gridtext::richtext_grob(text=body, gp=gp, vp=vp)
grid::grid.draw(rtg)
  # vp, gpslide

```







# test split_text_grob



```{r}
t_1 <- "This is a sample text. "
t_2 <- "When longer than viewport width, "
t_3 <- "text will be split and add a break. "
t_4 <- "This text is separated into 5 objects, "
t_5 <- "because of R document specification."
text <- stringr::str_c(t_1, t_2, t_3, t_4, t_5)
vp <- viewport(gp=gpar(fontsize=20))
pushViewport(vp)
st <- splitString(text)
grid.draw(textGrob(st, x=0, y=1, just=c("left", "top")))
  # grid.draw(textGrob(st, x=0, y=1, just=c("left", "top"), vp=vp))
popViewport()
```

# Arrange grobs

## Text grobs

```{r text_grob, warning=FALSE}
txt_tiny     <- "tiny"
txt_script   <- "script"
txt_footnote <- "footnote"
txt_caption  <- "caption"
txt_body     <- "body"
txt_BODY     <- "BODY"
txt_item     <- "item"
txt_ITEM     <- "ITEM"
txt_thank    <- "thank"
txt_author   <- "author"
txt_affil    <- "affil"
txt_subt     <- "subt"
txt_kw       <- "kw"
txt_title    <- "title"

tg_layout_1 <- arrange_txt(txt_tiny, txt_script, txt_footnote, txt_caption, txt_body, txt_BODY, txt_item, txt_ITEM)
tg_layout_2 <- arrange_txt(txt_thank, txt_author, txt_affil, txt_subt, txt_kw, txt_title)

grid::grid.draw(tg_layout_1)
grid::grid.draw(tg_layout_2)
```


## Combine ggobject and text grob 

You can combine ggplot object and text grob using gridExtra package. 

At first, generate ggplot object as below. 

```{r gg_obj, warning=FALSE}
gg_obj <- 
  ggplot2::ggplot(mpg) + 
  ggplot2::geom_point(aes(x = displ, y = hwy)) +
  ggplot2::theme_bw()
gg_obj  # draw ggplot object
```


```{r text}

  # tb <- txt2tibble(txt_body_1, txt_body_2, txt_body_3)
  # tb <- 
  # dplyr::mutate(font_size = purrr::pmap_dbl(tb, get_font_size)) %>%
  # dplyr::mutate(just="left") %>%
  # purrr::pmap(as_tg)
  # layout <- tg2layout(tg)
  # ar_tg <- tg_arrange(tg=tg, layout=layout)
```

Then, generate text grob as below. 
```{r text_grob2, warning=FALSE}
txt_body_1 <- "This graphics was generated using ggplot2. "
txt_body_2 <- "x axis is displ that means engine displacement in litres."
txt_body_3 <- "y axis is hwy that means highway miles per gallon."

tg_grob <- arrange_txt(txt_body_1, txt_body_2, txt_body_3)
grid::grid.draw(tg_grob)
grid::grid.newpage
```

Next, combine
```{r combine_gg_text, warning=FALSE}
gg_and_text <- gridExtra::grid.arrange(gg_obj, tg_grob, nrow=1, respect=c(TRUE, FALSE), widths=c(1,2))
grid::grid.draw(gg_and_text)
```

<!--
http://www.sthda.com/english/wiki/wiki.php?id_contents=7930
-->


# Generate a poster 

## Title

```{r title, warning=FALSE}
txt_title_1 <- "This is a title."
txt_ITEM_1 <- "ITEM text is larger than item text."
txt_item_2 <- "This is a item text, too."
txt_BODY_1 <- "BODY text is larger than body text."
txt_body_2 <- "This is a body text, too."
arranged_txt <- arrange_txt(txt_title_1, txt_ITEM_1, txt_item_2, txt_BODY_1, txt_body_2)
grid::grid.draw(arranged_txt)
```

```{r}
t_1 <- "This is a sample text. "
t_2 <- "When longer than viewport width, "
t_3 <- "text will be split and add a break. "
t_4 <- "This text is separated into 5 objects, "
t_5 <- "because of R document specification."
text <- stringr::str_c(t_1, t_2, t_3, t_4, t_5)
splitText <- split_text_grob(text)
grid::grid.draw(splitText)
```

# Sample


```{r sample_two_colmns, warning=FALSE}
txt_title  <- "wameicheckr"
  # txt_subt   <- ""
txt_author <- "Toshikazu Matsumura (Konan Women's univ.)"
  # txt_affil  <- ""
  # txt_thank  <- ""
txt_kw     <- "keywords: analysis，databese, search species names"
```

```{r warning=FALSE}
txt_title     <- "title"
txt_author    <- "author"
txt_kw        <- "keywords"

tg_header <- arrange_txt(txt_title, txt_author, txt_kw)
grid::grid.draw(tg_header)
```

# References

- Code in『R graphics』 by Paul Murell
  - [1st edition]( https://www.stat.auckland.ac.nz/~paul/RGraphics/rgraphics.html )
  - [2nd edition]( https://www.stat.auckland.ac.nz/~paul/RG2e/ )
  - [3rd edition]( https://www.stat.auckland.ac.nz/~paul/RG3e/ )

<!--
  - https://stat-ata-asu.github.io/R_DS_BD2020/using-ggplot2.html
  - https://www.christophenicault.com/post/understand_size_dimension_ggplot2/

  - ggplot2, grid, gtable, gridExtra
    - https://notchained.hatenablog.com/entry/2015/12/17/010904
    - https://github.com/baptiste/gridextra/wiki/arranging-ggplot

  - gtable
    - https://cran.r-project.org/web/packages/gridExtra/vignettes/gtable.html
    - https://github.com/r-lib/gtable


# slide number function, but no need cf. grid:::grobAutoName

slide_no <- function(){
  res <- 
    grid::grid.ls(print=FALSE) %>%
    .$name
  if(length(res)==0) return(1)
  res <- 
    res %>%
    stringr::str_subset("slide") %>%
    stringr::str_split("\\.|_") %>%
    unlist() %>%
    stringr::str_subset("\\d")
  if(length(res)==0) return(1)
  return( max(as.numeric(res)) + 1)
}

-->
