#' Fix table grob width and length to "mm"
#' 
#' The width and length of table grob generated by gridExtra::tableGrob() 
#' might not be correct. This function fix the width and length of table grob
#' to arrange table grobs at correct position. 
#' Not to use under other situations because of a table grob returned does not fit resized viewpot. 
#' 
#' @param tg A table grob. 
#' @return tableGrob
#' @examples
#' font_size_table <- 
#'   font_size_list %>%
#'   dplyr::filter(base_size==26) %>%
#'   gridExtra::tableGrob(rows=NULL)
#' base_size_table <- 
#'   font_size_list %>%
#'   dplyr::filter(ratio==1) %>%
#'   gridExtra::tableGrob(rows=NULL)
#' font_size_table <- fix_table_unit(font_size_table)
#' base_size_table <- fix_table_unit(base_size_table)
#' apposed_fixed <- appose_grobs(font_size_table, base_size_table, space=grid::unit(2, "mm"))
#' grid::grid.draw(apposed_fixed)
#' 
#' @export
fix_table_unit <- function(tg){
  tg$widths  <- grid::convertUnit(tg$widths,  "mm")
  tg$heights <- grid::convertUnit(tg$heights, "mm")
  tg
}

#' Generate booktab table grob 
#' 
#' @param tg             A table grob. 
#' @param df             A data frame. 
#' @param lwd_out,lwd_in A numeric. Line width. 
#' @param title,caption  A string. 
#' @param space          grid unit. Space between grobs. 
#' @return tableGrob
#' 
#' @name table_grob
#' @export
booktab_table_grob <- function(df, lwd_out=2, lwd_in=1, title=NULL, caption=NULL){
  df %>%
    gridExtra::tableGrob(rows=NULL, theme=gridExtra::ttheme_minimal()) %>%
    add_booktab(lwd_out=lwd_out, lwd_in=lwd_in) %>%
    add_annotation(title, caption)
}

#' Add book tab to table grob
#' 
#' @rdname table_grob
#' @export
add_booktab <- function(tg, lwd_out=2, lwd_in=1){
  tg %>%
    add_btw_line(lwd_in=lwd_in) %>%
    fix_table_unit() %>%
    add_tb_line(lwd_out=lwd_out)
}

#' Add line between colnames and values to table grob
#' 
#' @rdname table_grob
#' @export
add_btw_line <- function(tg, lwd_in=1){
  gtable::gtable_add_grob(tg, 
    grobs=grid::segmentsGrob(
      x0=grid::unit(0,"npc"), y0=grid::unit(0,"npc"),
      x1=grid::unit(1,"npc"), y1=grid::unit(0,"npc"),
      gp=grid::gpar(lwd=lwd_in)), t=1, b=1, l=1, r=ncol(tg))
}

#' Add top and bottom line to table grob
#' 
#' @rdname table_grob
#' @export
add_tb_line <- function(tg, lwd_out=2, space=grid::unit(0.1, "mm")){
  rect_height <- grid::unit(0.1, "mm")
  rg <- 
    grid::rectGrob(width=sum(tg$widths), 
             height=rect_height,
             gp=grid::gpar(lwd=lwd_out))
  sg <- stack_grobs(rg, tg, rg, space=space)
}

#' Add annotation to table grob
#' 
#' @rdname table_grob
#' @export
add_annotation <- function(tg, title=NULL, caption=NULL, space=grid::unit(3, "mm")){
  if(is.null(title) & is.null(caption)){
    return(tg)
  }
  if(!is.null(title))   title   <- grid::textGrob(label=title)
  if(!is.null(caption)) caption <- grid::textGrob(label=caption)
  stack_grobs(title, tg, caption, space=space)
}
