#' Fix table grob width and length to 'mm'
#'
#' The width and length of table grob generated by gridExtra::tableGrob()
#' might not be correct. This function fix the width and length of table grob
#' to arrange table grobs at correct position.
#' Not to use under other situations because of a table grob returned does not fit resized viewpot.
#'
#' @param tg A table grob.
#' @return tableGrob
#' @examples
#' font_size_table <-
#'   font_size_list %>%
#'   dplyr::filter(base_size == 26) %>%
#'   gridExtra::tableGrob(rows = NULL)
#' base_size_table <-
#'   font_size_list %>%
#'   dplyr::filter(ratio == 1) %>%
#'   gridExtra::tableGrob(rows = NULL)
#' font_size_table <- fix_table_unit(font_size_table)
#' base_size_table <- fix_table_unit(base_size_table)
#' apposed_fixed <- 
#'      combine_grobs(font_size_table, base_size_table, 
#'      direction = "horizontal", unify = "as_is", space = grid::unit(2, "mm"))
#' grid::grid.draw(apposed_fixed)
#'
#' @export
fix_table_unit <- function(tg) {
  tg$widths <- grid::convertUnit(tg$widths, "mm")
  tg$heights <- grid::convertUnit(tg$heights, "mm")
  tg
}

#' Generate booktab table grob
#'
#' @param tg             A table grob.
#' @param df             A data frame.
#' @param title,caption  A string.
#' @param title_size     A numeric.
#' @param fontsize       A numeric specified by pt.
#' @param shrink         A numeric.
#' @param lwd_out,lwd_in A numeric. Line width.
#' @param space          grid unit. Space between grobs.
#' @return tableGrob
#'
#' @name table_grob
#' @export
booktab_table_grob <- function(df, title = NULL, caption = NULL, 
                               title_size = 1.2, 
                               fontsize = NULL, shrink = 1, lwd_out = 2, lwd_in = 1) {
  if (is.null(fontsize)) {
    fontsize <- grid::get.gpar()$fontsize
  }
  fontsize <- fontsize * shrink
  lwd_out <- lwd_out * shrink
  lwd_in <- lwd_in * shrink
  tg <- 
    df %>%
    gridExtra::tableGrob(rows = NULL, theme = gridExtra::ttheme_minimal(base_size = fontsize)) %>%
    add_booktab(lwd_out = lwd_out, lwd_in = lwd_in)
  shoot(add_annotation, tg, title, caption, fontsize, title_size)
}

#' Add book tab to table grob
#'
#' @rdname table_grob
#' @export
add_booktab <- function(tg, lwd_out = 2, lwd_in = 1) {
  tg %>%
    add_inner_line(lwd_in = lwd_in) %>%
    fix_table_unit() %>%
    add_outer_line(lwd_out = lwd_out)
}

#' Add line between colnames and values to table grob
#'
#' @rdname table_grob
#' @export
add_inner_line <- function(tg, lwd_in = 1) {
  gtable::gtable_add_grob(tg,
    grobs = grid::segmentsGrob(
       x0 = grid::unit(0, "npc"), y0 = grid::unit(0, "npc"), 
       x1 = grid::unit(1, "npc"), y1 = grid::unit(0, "npc"), 
       gp = grid::gpar(lwd = lwd_in)),
       t = 1, b = 1, l = 1, r = ncol(tg))
}

#' Add top and bottom line to table grob
#'
#' @rdname table_grob
#' @export
add_outer_line <- function(tg, lwd_out = 2, space = grid::unit(1, "mm")) {
  rect_height <- grid::unit(0.1, "mm")
  rg <- grid::rectGrob(width = sum(tg$widths), height = rect_height, gp = grid::gpar(lwd = lwd_out))
  sg <- combine_grobs(rg, tg, rg, direction = "vertical", unify = "width", space = space)
}

#' Add annotation to table grob
#'
#' @rdname table_grob
#' @export
add_annotation <- function(tg, title = NULL, caption = NULL, 
                           title_size = 1.2, 
                           fontsize = NULL, space = NULL) {
  if (is.null(title) & is.null(caption)) return(tg)
  if (is.null(fontsize)) fontsize <- grid::get.gpar()$fontsize
  if (!is.null(title)) {
    title <- 
      gridtext::textbox_grob(
        text = title, width = grob_widths(tg), x = 0, hjust = 0, 
        gp = grid::gpar(fontsize = fontsize * title_size), use_markdown = FALSE)
  }
  if (!is.null(caption)) {
    caption <- 
      gridtext::textbox_grob(
        text = caption, width = grob_widths(tg), x = 0, hjust = 0, 
        gp = grid::gpar(fontsize = fontsize), use_markdown = FALSE)
  }
  if (is.null(space)) {
    min_ratio <- 0.2 # 
    space_t <- if (is.null(title))   grid::unit(0, "mm") else grob_heights(title,   convert_to="mm") * min_ratio
    space_c <- if (is.null(caption)) grid::unit(0, "mm") else grob_heights(caption, convert_to="mm") * min_ratio
    space <- min(space_t, space_c, grid::unit(1, "mm"))
  }
  combine_grobs(title, tg, caption, direction = "vertical", unify = "as_is", space = space)
}
